export function getRuntimeEnv(_locals?: App.Locals): RuntimeEnv {
  return {
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    CONTACT_FROM_EMAIL: process.env.CONTACT_FROM_EMAIL,
    DATABASE_CA_CERT: process.env.DATABASE_CA_CERT,
    DATABASE_URL: process.env.DATABASE_URL,
    LOCAL_ADMIN_CODE: process.env.LOCAL_ADMIN_CODE,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    BUFFER_API_KEY: process.env.BUFFER_API_KEY,
    MEDIA_URL_SIGNING_SECRET: process.env.MEDIA_URL_SIGNING_SECRET,
    MEDIA_URL_SIGNING_SECRET_NEXT: process.env.MEDIA_URL_SIGNING_SECRET_NEXT,
    R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID,
    R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID,
    R2_BUCKET: process.env.R2_BUCKET,
    R2_ENDPOINT: process.env.R2_ENDPOINT,
    R2_MEDIA_BASE_URL: process.env.R2_MEDIA_BASE_URL,
    R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY,
    SESSION_SECRET: process.env.SESSION_SECRET,
    TURNSTILE_SECRET_KEY: process.env.TURNSTILE_SECRET_KEY,
    TURNSTILE_SITE_KEY: process.env.TURNSTILE_SITE_KEY,
  };
}
